package com.auvan.api.outbox.entity;

public enum OutboxEventType {
    BOOKING_CREATED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    PAYMENT_PROOF_SUBMITTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    DEPARTURE_REMINDER_24H,
    DEPARTURE_REMINDER_1H,
    WAITLIST_PROMOTED,
    WAITLIST_PROMOTION_EXPIRED
}
